services:
  db:
    container_name: springapp
    image: postgres
    environment:
      POSTGRES_USER: hamzoo
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5532:5432"
    networks:
      - db
    restart: unless-stopped
networks:
  db:
    driver: bridge
volumes:
  db: